import type { Category, Flashcard, SentenceExercise } from '@/types'

export const CATEGORIES: Omit<Category, never>[] = [
  { id: 1,  name: 'Daily Standup',      namePT: 'Daily Standup',       icon: '☀️', color: '#64FFDA', description: 'Frases do daily e status updates' },
  { id: 2,  name: 'Retrospectiva',      namePT: 'Retrospectiva',       icon: '🔄', color: '#FF7B7B', description: 'O que foi bem, mal e ações' },
  { id: 3,  name: 'Sprint Planning',    namePT: 'Sprint Planning',     icon: '📋', color: '#7BED9F', description: 'Planning, estimativas e escopo' },
  { id: 4,  name: 'Quarter Planning',   namePT: 'Quarter Planning',    icon: '📊', color: '#FFD32A', description: 'OKRs, roadmap e estratégia' },
  { id: 5,  name: 'Alinhamentos',       namePT: 'Alinhamentos',        icon: '🤝', color: '#A29BFE', description: 'Sincronia, decisões e comunicação' },
  { id: 6,  name: 'Present Tenses',     namePT: 'Tempos do Presente',  icon: '⚡', color: '#64FFDA', description: 'Simple, Continuous, Perfect' },
  { id: 7,  name: 'Past Tenses',        namePT: 'Tempos do Passado',   icon: '⏪', color: '#FF7B7B', description: 'Simple, Continuous, Perfect' },
  { id: 8,  name: 'Future Tenses',      namePT: 'Tempos do Futuro',    icon: '⏩', color: '#7BED9F', description: 'Will, Going To, Future Perfect' },
  { id: 9,  name: 'Conditionals',       namePT: 'Condicionais',        icon: '🔀', color: '#FFD32A', description: 'If clauses: 0, 1st, 2nd, 3rd' },
  { id: 10, name: 'Modal Verbs',        namePT: 'Verbos Modais',       icon: '🎯', color: '#A29BFE', description: 'Can, Should, Must, Would...' },
  { id: 11, name: 'Contractions',       namePT: 'Contrações',          icon: '✂️', color: '#74B9FF', description: "I'm, won't, haven't, couldn't..." },
  { id: 12, name: 'Tech Vocabulary',    namePT: 'Vocabulário Tech',    icon: '💻', color: '#FD79A8', description: 'Verbos, termos e expressões tech' },
  { id: 13, name: 'Code Review',        namePT: 'Revisão de Código',   icon: '🔍', color: '#A29BFE', description: 'Frases de code review' },
  { id: 14, name: 'Incident Management',namePT: 'Gestão de Incidentes',icon: '🚨', color: '#FF7B7B', description: 'Gestão de incidentes e alertas' },
  { id: 15, name: 'Business Communication', namePT: 'Comunicação Profissional', icon: '💼', color: '#00D9FF', description: 'Comunicação efetiva no ambiente corporativo' },
  { id: 16, name: 'Tense Tips & Tricks',   namePT: 'Dicas de Tempos Verbais', icon: '🎓', color: '#FFB800', description: '6 dicas práticas para usar os tempos certos' },
]

type FCInput = Omit<Flashcard, 'id'>
type SEInput = Omit<SentenceExercise, 'id'>

export const FLASHCARDS: FCInput[] = [
  // ── Category 1: Daily Standup ──────────────────────────────────────────
  { categoryId:1, englishText:"I'm blocked on...",           portugueseText:"Estou bloqueado em...",            exampleSentence:"I'm blocked on the API integration — waiting for credentials.", exampleTranslation:"Estou bloqueado na integração de API — aguardando credenciais.", verbTense:"Present Continuous", type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"No blockers for me today",    portugueseText:"Sem bloqueios pra mim hoje",       exampleSentence:"No blockers for me today. I'll keep pushing on the migration.",  exampleTranslation:"Sem bloqueios pra mim hoje. Vou continuar na migração.",       verbTense:"Simple Present",    type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"Yesterday I worked on...",    portugueseText:"Ontem trabalhei em...",            exampleSentence:"Yesterday I worked on the authentication module.",               exampleTranslation:"Ontem trabalhei no módulo de autenticação.",                   verbTense:"Simple Past",       type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"Today I'm going to...",       portugueseText:"Hoje vou...",                     exampleSentence:"Today I'm going to finish the unit tests.",                       exampleTranslation:"Hoje vou terminar os testes unitários.",                       verbTense:"Going To",          type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"I'm almost done with...",     portugueseText:"Estou quase terminando...",       exampleSentence:"I'm almost done with the code review.",                           exampleTranslation:"Estou quase terminando o code review.",                        verbTense:"Present Continuous",type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"It's in review",              portugueseText:"Está em review",                 exampleSentence:"The PR is in review — waiting for at least one approval.",        exampleTranslation:"O PR está em review — aguardando pelo menos uma aprovação.",    verbTense:"Simple Present",    type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"I pushed the fix",            portugueseText:"Mandei o fix",                   exampleSentence:"I pushed the fix to the feature branch.",                         exampleTranslation:"Mandei o fix para a branch da feature.",                       verbTense:"Simple Past",       type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"I'll sync with...",           portugueseText:"Vou sincronizar com...",         exampleSentence:"I'll sync with the backend team after standup.",                  exampleTranslation:"Vou sincronizar com o time de backend depois do standup.",      verbTense:"Simple Future",     type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"I'm pairing with...",         portugueseText:"Estou fazendo pair com...",      exampleSentence:"I'm pairing with Sarah today on the database migration.",          exampleTranslation:"Estou fazendo pair com a Sarah hoje na migração do banco.",     verbTense:"Present Continuous",type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"I wrapped up...",             portugueseText:"Terminei...",                    exampleSentence:"I wrapped up the refactoring and opened the PR.",                  exampleTranslation:"Terminei a refatoração e abri o PR.",                          verbTense:"Simple Past",       type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"Waiting on feedback from...", portugueseText:"Aguardando feedback de...",      exampleSentence:"I'm waiting on feedback from the design team.",                    exampleTranslation:"Estou aguardando feedback do time de design.",                  verbTense:"Present Continuous",type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"I'll pick that up",           portugueseText:"Vou pegar isso",                 exampleSentence:"I'll pick that ticket up once I finish the current task.",         exampleTranslation:"Vou pegar esse ticket assim que terminar a tarefa atual.",      verbTense:"Simple Future",     type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"Can we sync after standup?",  portugueseText:"Podemos sincronizar depois do standup?", exampleSentence:"Can we sync after standup to discuss the architecture?", exampleTranslation:"Podemos sincronizar depois do standup para discutir a arquitetura?", verbTense:"Simple Present", type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"It's deployed",               portugueseText:"Está deployed",                  exampleSentence:"The hotfix is deployed to production.",                           exampleTranslation:"O hotfix está deployed em produção.",                          verbTense:"Simple Present",    type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"I need help with...",         portugueseText:"Preciso de ajuda com...",        exampleSentence:"I need help with the database query optimization.",                exampleTranslation:"Preciso de ajuda com a otimização de query do banco.",          verbTense:"Simple Present",    type:"Phrase",      difficulty:2, contextTag:"Daily" },
  { categoryId:1, englishText:"I have a dependency on...",   portugueseText:"Tenho uma dependência em...",    exampleSentence:"I have a dependency on the DevOps team for the credentials.",      exampleTranslation:"Tenho uma dependência no time de DevOps para as credenciais.",  verbTense:"Simple Present",    type:"Phrase",      difficulty:2, contextTag:"Daily" },
  { categoryId:1, englishText:"I spent most of the day...",  portugueseText:"Passei a maior parte do dia...", exampleSentence:"I spent most of the day investigating the performance issue.",    exampleTranslation:"Passei a maior parte do dia investigando o problema de performance.", verbTense:"Simple Past",  type:"Phrase",      difficulty:2, contextTag:"Daily" },
  { categoryId:1, englishText:"I'll take this ticket",       portugueseText:"Vou pegar esse ticket",          exampleSentence:"I'll take this ticket since no one else picked it up.",            exampleTranslation:"Vou pegar esse ticket já que ninguém pegou ainda.",            verbTense:"Simple Future",     type:"Phrase",      difficulty:1, contextTag:"Daily" },
  { categoryId:1, englishText:"Waiting for code review",     portugueseText:"Aguardando revisão de código",   exampleSentence:"I'm waiting for code review on my last PR.",                       exampleTranslation:"Estou aguardando revisão de código no meu último PR.",          verbTense:"Present Continuous",type:"Phrase",      difficulty:1, contextTag:"standup" },
  { categoryId:1, englishText:"PR is under review",          portugueseText:"PR está em revisão",             exampleSentence:"My PR is under review — should be merged today.",                  exampleTranslation:"Meu PR está em revisão — deve ser mergeado hoje.",             verbTense:"Present",           type:"Phrase",      difficulty:1, contextTag:"standup" },
  { categoryId:1, englishText:"Will be done by end of day",  portugueseText:"Estará pronto até o fim do dia", exampleSentence:"This task will be done by end of day.",                           exampleTranslation:"Essa tarefa estará pronta até o fim do dia.",                  verbTense:"Future Simple",     type:"Phrase",      difficulty:1, contextTag:"standup" },

  // ── Category 2: Retrospectiva ──────────────────────────────────────────
  { categoryId:2, englishText:"What went well",              portugueseText:"O que foi bem",                  exampleSentence:"What went well this sprint was our team communication.",           exampleTranslation:"O que foi bem nessa sprint foi a comunicação do time.",         verbTense:"Simple Past",       type:"Phrase",      difficulty:1, contextTag:"Retro" },
  { categoryId:2, englishText:"What didn't go well",         portugueseText:"O que não foi bem",              exampleSentence:"What didn't go well was the lack of clear requirements.",          exampleTranslation:"O que não foi bem foi a falta de requisitos claros.",          verbTense:"Simple Past",       type:"Phrase",      difficulty:1, contextTag:"Retro" },
  { categoryId:2, englishText:"Action item",                 portugueseText:"Item de ação",                   exampleSentence:"The action item is to set up better monitoring by next Friday.",   exampleTranslation:"O item de ação é configurar um monitoramento melhor até a próxima sexta.", verbTense:"Simple Present", type:"Phrase", difficulty:1, contextTag:"Retro" },
  { categoryId:2, englishText:"We should have...",           portugueseText:"Deveríamos ter...",              exampleSentence:"We should have tested this before deploying to production.",       exampleTranslation:"Deveríamos ter testado isso antes de fazer deploy em produção.", verbTense:"Past Perfect",      type:"Phrase",      difficulty:2, contextTag:"Retro" },
  { categoryId:2, englishText:"Going forward",               portugueseText:"Daqui pra frente",               exampleSentence:"Going forward, we should add monitoring to every new service.",    exampleTranslation:"Daqui pra frente, devemos adicionar monitoramento a cada novo serviço.", verbTense:"Simple Present", type:"Expression", difficulty:1, contextTag:"Retro" },
  { categoryId:2, englishText:"Root cause",                  portugueseText:"Causa raiz",                     exampleSentence:"The root cause of the incident was a missing index.",              exampleTranslation:"A causa raiz do incidente foi um index faltando.",             verbTense:"Simple Past",       type:"Expression",  difficulty:2, contextTag:"Retro" },
  { categoryId:2, englishText:"We underestimated...",        portugueseText:"Subestimamos...",                exampleSentence:"We underestimated the complexity of the migration task.",          exampleTranslation:"Subestimamos a complexidade da tarefa de migração.",           verbTense:"Simple Past",       type:"Phrase",      difficulty:2, contextTag:"Retro" },
  { categoryId:2, englishText:"We could improve...",         portugueseText:"Poderíamos melhorar...",         exampleSentence:"We could improve our code review process going forward.",          exampleTranslation:"Poderíamos melhorar nosso processo de code review daqui pra frente.", verbTense:"Conditional", type:"Phrase",      difficulty:2, contextTag:"Retro" },
  { categoryId:2, englishText:"That's a great win",          portugueseText:"Isso é uma grande vitória",      exampleSentence:"Shipping all committed tickets — that's a great win for the team.", exampleTranslation:"Entregar todos os tickets comprometidos — isso é uma grande vitória.", verbTense:"Simple Present", type:"Expression", difficulty:1, contextTag:"Retro" },
  { categoryId:2, englishText:"This slowed us down",         portugueseText:"Isso nos atrasou",               exampleSentence:"The unclear requirements really slowed us down.",                  exampleTranslation:"Os requisitos pouco claros realmente nos atrasaram.",           verbTense:"Simple Past",       type:"Expression",  difficulty:1, contextTag:"Retro" },
  { categoryId:2, englishText:"We've improved...",           portugueseText:"Melhoramos...",                  exampleSentence:"We've improved our deployment frequency this quarter.",            exampleTranslation:"Melhoramos nossa frequência de deploy nesse trimestre.",        verbTense:"Present Perfect",   type:"Phrase",      difficulty:2, contextTag:"Retro" },
  { categoryId:2, englishText:"Post-mortem",                 portugueseText:"Análise pós-incidente",          exampleSentence:"We'll hold a post-mortem to understand the root cause.",           exampleTranslation:"Faremos uma análise pós-incidente para entender a causa raiz.",verbTense:"Simple Future",     type:"Expression",  difficulty:2, contextTag:"Retro" },

  // ── Category 3: Sprint Planning ────────────────────────────────────────
  { categoryId:3, englishText:"Story points",                portugueseText:"Story points",                   exampleSentence:"I'd estimate this at around 5 story points.",                     exampleTranslation:"Estimaria isso em torno de 5 story points.",                   verbTense:"Conditional",       type:"Vocabulary",  difficulty:1, contextTag:"Planning" },
  { categoryId:3, englishText:"velocity",                    portugueseText:"velocidade do time",             exampleSentence:"Our velocity this sprint was 42 points.",                         exampleTranslation:"Nossa velocidade nesse sprint foi de 42 pontos.",              verbTense:"Past Simple",       type:"Noun",        difficulty:2, contextTag:"planning" },
  { categoryId:3, englishText:"acceptance criteria",         portugueseText:"critérios de aceitação",         exampleSentence:"Let's define the acceptance criteria for this story.",             exampleTranslation:"Vamos definir os critérios de aceitação para essa história.",  verbTense:"Present",           type:"Expression",  difficulty:2, contextTag:"planning" },
  { categoryId:3, englishText:"spike",                       portugueseText:"spike / pesquisa técnica",       exampleSentence:"Let's create a spike to investigate the new framework.",           exampleTranslation:"Vamos criar um spike para investigar o novo framework.",        verbTense:"Present",           type:"Expression",  difficulty:2, contextTag:"planning" },
  { categoryId:3, englishText:"This story is too big",       portugueseText:"Essa história é grande demais",  exampleSentence:"This story is too big for one sprint — let's split it.",           exampleTranslation:"Essa história é grande demais para um sprint — vamos dividi-la.", verbTense:"Present",           type:"Phrase",      difficulty:1, contextTag:"planning" },
  { categoryId:3, englishText:"grooming session",            portugueseText:"sessão de refinamento",          exampleSentence:"We have a grooming session every Wednesday.",                     exampleTranslation:"Temos uma sessão de refinamento toda quarta-feira.",            verbTense:"Present",           type:"Expression",  difficulty:1, contextTag:"planning" },
  { categoryId:3, englishText:"What is the priority order?", portugueseText:"Qual é a ordem de prioridade?",  exampleSentence:"What is the priority order for this sprint?",                     exampleTranslation:"Qual é a ordem de prioridade para esse sprint?",               verbTense:"Present",           type:"Phrase",      difficulty:1, contextTag:"planning" },

  // ── Category 7: Past Tenses ────────────────────────────────────────────
  { categoryId:7, englishText:"We had been experiencing slowdowns", portugueseText:"Estávamos experienciando lentidões", exampleSentence:"We had been experiencing slowdowns before the cache fix.", exampleTranslation:"Estávamos experienciando lentidões antes da correção do cache.", verbTense:"Past Perfect Continuous", type:"Phrase", difficulty:3, contextTag:"retrospective" },
  { categoryId:7, englishText:"The deployment failed",       portugueseText:"O deploy falhou",                exampleSentence:"The deployment failed due to a config mismatch.",                  exampleTranslation:"O deploy falhou por causa de uma incompatibilidade de configuração.", verbTense:"Past Simple", type:"Phrase", difficulty:1, contextTag:"incident" },
  { categoryId:7, englishText:"By the time we noticed, users had already left", portugueseText:"Quando percebemos, os usuários já tinham saído", exampleSentence:"By the time we noticed, users had already left the funnel.", exampleTranslation:"Quando percebemos, os usuários já tinham abandonado o funil.", verbTense:"Past Perfect", type:"Phrase", difficulty:3, contextTag:"retrospective" },

  // ── Category 8: Future Tenses ──────────────────────────────────────────
  { categoryId:8, englishText:"We are going to refactor the module",   portugueseText:"Vamos refatorar o módulo",           exampleSentence:"We are going to refactor the authentication module next sprint.", exampleTranslation:"Vamos refatorar o módulo de autenticação no próximo sprint.", verbTense:"Going To",          type:"Phrase",      difficulty:1, contextTag:"planning" },
  { categoryId:8, englishText:"The feature will be released next week",portugueseText:"A funcionalidade será lançada na próxima semana", exampleSentence:"The feature will be released next week after QA approval.", exampleTranslation:"A funcionalidade será lançada na próxima semana após aprovação de QA.", verbTense:"Future Simple", type:"Phrase", difficulty:1, contextTag:"planning" },
  { categoryId:8, englishText:"By Friday, I will have finished the PR",portugueseText:"Até sexta, terei terminado o PR",   exampleSentence:"By Friday, I will have finished the PR and tests.",               exampleTranslation:"Até sexta, terei terminado o PR e os testes.",                verbTense:"Future Perfect",    type:"Phrase",      difficulty:3, contextTag:"standup" },

  // ── Category 9: Conditionals ───────────────────────────────────────────
  { categoryId:9, englishText:"If it breaks in production, we will roll back", portugueseText:"Se quebrar em produção, vamos reverter", exampleSentence:"If it breaks in production, we will roll back immediately.", exampleTranslation:"Se quebrar em produção, vamos reverter imediatamente.", verbTense:"First Conditional", type:"Phrase", difficulty:2, contextTag:"planning" },
  { categoryId:9, englishText:"Unless we fix the bug, users will be affected", portugueseText:"A menos que corrijamos o bug, os usuários serão afetados", exampleSentence:"Unless we fix the bug, users will be affected all week.", exampleTranslation:"A menos que corrijamos o bug, os usuários serão afetados a semana toda.", verbTense:"First Conditional", type:"Phrase", difficulty:3, contextTag:"incident" },
  { categoryId:9, englishText:"Provided that the tests pass, we can deploy", portugueseText:"Desde que os testes passem, podemos fazer deploy", exampleSentence:"Provided that the tests pass, we can deploy tonight.", exampleTranslation:"Desde que os testes passem, podemos fazer deploy hoje à noite.", verbTense:"First Conditional", type:"Phrase", difficulty:3, contextTag:"deployment" },
  { categoryId:9, englishText:"If we had added more tests we would not have shipped the bug", portugueseText:"Se tivéssemos adicionado mais testes não teríamos lançado o bug", exampleSentence:"If we had added more tests we would not have shipped the bug.", exampleTranslation:"Se tivéssemos adicionado mais testes não teríamos lançado o bug.", verbTense:"Third Conditional", type:"Phrase", difficulty:3, contextTag:"retrospective" },

  // ── Category 10: Modal Verbs ───────────────────────────────────────────
  { categoryId:10, englishText:"You should refactor this",     portugueseText:"Você deveria refatorar isso",       exampleSentence:"You should refactor this before it gets worse.",                exampleTranslation:"Você deveria refatorar isso antes que piore.",                verbTense:"Modal",             type:"Phrase",      difficulty:1, contextTag:"code-review" },
  { categoryId:10, englishText:"We ought to write documentation",portugueseText:"Deveríamos escrever documentação", exampleSentence:"We ought to write documentation for this API.",                  exampleTranslation:"Deveríamos escrever documentação para essa API.",              verbTense:"Modal",             type:"Phrase",      difficulty:2, contextTag:"development" },
  { categoryId:10, englishText:"This might be a timeout issue", portugueseText:"Isso pode ser um problema de timeout", exampleSentence:"This might be a timeout issue — increase the limit.",       exampleTranslation:"Isso pode ser um problema de timeout — aumente o limite.",    verbTense:"Modal",             type:"Phrase",      difficulty:2, contextTag:"debugging" },
  { categoryId:10, englishText:"You should have written tests before submitting the PR", portugueseText:"Você deveria ter escrito testes antes de enviar o PR", exampleSentence:"You should have written tests before submitting the PR.", exampleTranslation:"Você deveria ter escrito testes antes de enviar o PR.", verbTense:"Modal Perfect", type:"Phrase", difficulty:3, contextTag:"code-review" },

  // ── Category 12: Tech Vocabulary ───────────────────────────────────────
  { categoryId:12, englishText:"load balancer",               portugueseText:"balanceador de carga",            exampleSentence:"The load balancer distributes traffic across servers.",           exampleTranslation:"O balanceador de carga distribui o tráfego entre servidores.", verbTense:"",                  type:"Noun",        difficulty:2, contextTag:"infrastructure" },
  { categoryId:12, englishText:"caching layer",               portugueseText:"camada de cache",                 exampleSentence:"Add a caching layer to improve response time.",                    exampleTranslation:"Adicione uma camada de cache para melhorar o tempo de resposta.", verbTense:"",               type:"Noun",        difficulty:2, contextTag:"infrastructure" },
  { categoryId:12, englishText:"API gateway",                 portugueseText:"gateway de API",                  exampleSentence:"All requests go through the API gateway.",                        exampleTranslation:"Todas as requisições passam pelo gateway de API.",             verbTense:"",                  type:"Noun",        difficulty:2, contextTag:"infrastructure" },
  { categoryId:12, englishText:"message queue",               portugueseText:"fila de mensagens",               exampleSentence:"Use a message queue to decouple the services.",                    exampleTranslation:"Use uma fila de mensagens para desacoplar os serviços.",       verbTense:"",                  type:"Noun",        difficulty:2, contextTag:"infrastructure" },
  { categoryId:12, englishText:"feature flag",                portugueseText:"flag de funcionalidade",          exampleSentence:"Use a feature flag to roll out gradually.",                       exampleTranslation:"Use um flag de funcionalidade para lançar gradualmente.",      verbTense:"",                  type:"Expression",  difficulty:2, contextTag:"development" },
  { categoryId:12, englishText:"observability",               portugueseText:"observabilidade",                 exampleSentence:"Good observability means logs, metrics and traces.",               exampleTranslation:"Boa observabilidade significa logs, métricas e rastreamentos.", verbTense:"",                  type:"Noun",        difficulty:3, contextTag:"monitoring" },
  { categoryId:12, englishText:"race condition",              portugueseText:"condição de corrida",             exampleSentence:"There is a race condition when two threads write simultaneously.",  exampleTranslation:"Há uma condição de corrida quando duas threads escrevem simultaneamente.", verbTense:"Present", type:"Expression", difficulty:3, contextTag:"concurrency" },
  { categoryId:12, englishText:"memory leak",                 portugueseText:"vazamento de memória",            exampleSentence:"The memory leak caused the service to crash overnight.",            exampleTranslation:"O vazamento de memória fez o serviço travar durante a noite.", verbTense:"Past Simple",       type:"Expression",  difficulty:2, contextTag:"debugging" },
  { categoryId:12, englishText:"dependency injection",        portugueseText:"injeção de dependência",          exampleSentence:"We use dependency injection to improve testability.",               exampleTranslation:"Usamos injeção de dependência para melhorar a testabilidade.", verbTense:"Present",           type:"Expression",  difficulty:3, contextTag:"architecture" },
  { categoryId:12, englishText:"idempotent",                  portugueseText:"idempotente",                     exampleSentence:"Make sure the endpoint is idempotent.",                           exampleTranslation:"Certifique-se de que o endpoint é idempotente.",               verbTense:"",                  type:"Adjective",   difficulty:3, contextTag:"api" },
  { categoryId:12, englishText:"canary deployment",           portugueseText:"deploy canário",                  exampleSentence:"We used a canary deployment to test the new version.",             exampleTranslation:"Usamos um deploy canário para testar a nova versão.",          verbTense:"Past Simple",       type:"Expression",  difficulty:3, contextTag:"devops" },
  { categoryId:12, englishText:"blue-green deployment",       portugueseText:"deploy blue-green",               exampleSentence:"Blue-green deployment allows zero-downtime releases.",             exampleTranslation:"O deploy blue-green permite lançamentos sem tempo de inatividade.", verbTense:"",             type:"Expression",  difficulty:3, contextTag:"devops" },
  { categoryId:12, englishText:"Infrastructure as Code (IaC)",portugueseText:"Infraestrutura como Código",      exampleSentence:"We manage all infrastructure using IaC tools like Terraform.",    exampleTranslation:"Gerenciamos toda a infraestrutura com ferramentas de IaC como Terraform.", verbTense:"", type:"Expression", difficulty:3, contextTag:"devops" },
  { categoryId:12, englishText:"distributed tracing",         portugueseText:"rastreamento distribuído",        exampleSentence:"Distributed tracing helps debug microservices.",                   exampleTranslation:"O rastreamento distribuído ajuda a depurar microsserviços.",   verbTense:"",                  type:"Expression",  difficulty:3, contextTag:"monitoring" },
  { categoryId:12, englishText:"MTTR – Mean Time To Recovery",portugueseText:"Tempo Médio de Recuperação",      exampleSentence:"We reduced the MTTR from 2 hours to 15 minutes.",                 exampleTranslation:"Reduzimos o MTTR de 2 horas para 15 minutos.",                 verbTense:"Past Simple",       type:"Acronym",     difficulty:3, contextTag:"incident" },
  { categoryId:12, englishText:"throughput",                  portugueseText:"taxa de transferência / throughput", exampleSentence:"The throughput increased after the optimization.",             exampleTranslation:"A taxa de transferência aumentou após a otimização.",          verbTense:"Past Simple",       type:"Noun",        difficulty:3, contextTag:"performance" },

  // ── Category 13: Code Review ───────────────────────────────────────────
  { categoryId:13, englishText:"LGTM – Looks Good To Me",     portugueseText:"Parece bom pra mim",              exampleSentence:"No major issues — LGTM!",                                         exampleTranslation:"Sem problemas maiores — parece bom!",                          verbTense:"Present",           type:"Acronym",     difficulty:1, contextTag:"code-review" },
  { categoryId:13, englishText:"nit (nitpick)",                portugueseText:"Detalhe menor / Fresco",          exampleSentence:"Nit: this variable name could be clearer.",                       exampleTranslation:"Detalhe: esse nome de variável poderia ser mais claro.",       verbTense:"",                  type:"Slang",       difficulty:1, contextTag:"code-review" },
  { categoryId:13, englishText:"blocking comment",             portugueseText:"Comentário bloqueador",           exampleSentence:"This is a blocking comment — we can't merge until it's fixed.",   exampleTranslation:"Este é um comentário bloqueador — não podemos fazer merge enquanto não for corrigido.", verbTense:"", type:"Expression", difficulty:2, contextTag:"code-review" },
  { categoryId:13, englishText:"non-blocking comment",         portugueseText:"Comentário não-bloqueador",       exampleSentence:"Just a non-blocking suggestion.",                                 exampleTranslation:"Apenas uma sugestão não-bloqueadora.",                         verbTense:"",                  type:"Expression",  difficulty:2, contextTag:"code-review" },
  { categoryId:13, englishText:"Could you add tests for this?",portugueseText:"Você poderia adicionar testes para isso?", exampleSentence:"Could you add tests for this edge case?",           exampleTranslation:"Você poderia adicionar testes para esse caso extremo?",        verbTense:"Conditional",       type:"Phrase",      difficulty:1, contextTag:"code-review" },
  { categoryId:13, englishText:"Please address the comments",  portugueseText:"Por favor, resolva os comentários", exampleSentence:"Please address the comments before requesting another review.", exampleTranslation:"Por favor, resolva os comentários antes de pedir outra revisão.", verbTense:"Imperative",     type:"Phrase",      difficulty:1, contextTag:"code-review" },
  { categoryId:13, englishText:"approved with minor comments", portugueseText:"aprovado com comentários menores", exampleSentence:"I approved it with minor comments.",                            exampleTranslation:"Aprovei com comentários menores.",                             verbTense:"Past Simple",       type:"Expression",  difficulty:1, contextTag:"code-review" },
  { categoryId:13, englishText:"This might cause a performance issue", portugueseText:"Isso pode causar um problema de performance", exampleSentence:"This loop might cause a performance issue at scale.", exampleTranslation:"Esse loop pode causar um problema de performance em escala.", verbTense:"Present", type:"Phrase", difficulty:2, contextTag:"code-review" },
  { categoryId:13, englishText:"Consider edge cases here",     portugueseText:"Considere casos extremos aqui",   exampleSentence:"Consider edge cases here — what if the list is empty?",           exampleTranslation:"Considere casos extremos aqui — e se a lista estiver vazia?",  verbTense:"Imperative",        type:"Phrase",      difficulty:2, contextTag:"code-review" },
  { categoryId:13, englishText:"duplicate code",               portugueseText:"código duplicado",                exampleSentence:"There is duplicate code in these two methods.",                   exampleTranslation:"Há código duplicado nesses dois métodos.",                     verbTense:"",                  type:"Expression",  difficulty:1, contextTag:"code-review" },
  { categoryId:13, englishText:"breaking change",              portugueseText:"mudança incompatível / breaking change", exampleSentence:"This is a breaking change — update the changelog.",   exampleTranslation:"Esta é uma mudança incompatível — atualize o changelog.",      verbTense:"",                  type:"Expression",  difficulty:2, contextTag:"code-review" },
  { categoryId:13, englishText:"dead code",                    portugueseText:"código morto",                    exampleSentence:"Remove the dead code before merging.",                            exampleTranslation:"Remova o código morto antes de fazer merge.",                  verbTense:"Imperative",        type:"Expression",  difficulty:1, contextTag:"code-review" },
  { categoryId:13, englishText:"magic number",                 portugueseText:"número mágico",                   exampleSentence:"Avoid magic numbers — use a named constant instead.",            exampleTranslation:"Evite números mágicos — use uma constante nomeada.",           verbTense:"",                  type:"Expression",  difficulty:2, contextTag:"code-review" },
  { categoryId:13, englishText:"happy path",                   portugueseText:"caminho feliz / fluxo principal", exampleSentence:"This only tests the happy path.",                                 exampleTranslation:"Isso só testa o caminho feliz.",                               verbTense:"",                  type:"Slang",       difficulty:2, contextTag:"code-review" },
  { categoryId:13, englishText:"I left some suggestions",      portugueseText:"Deixei algumas sugestões",        exampleSentence:"I left some suggestions but nothing blocking.",                   exampleTranslation:"Deixei algumas sugestões mas nada bloqueador.",                verbTense:"Past Simple",       type:"Phrase",      difficulty:1, contextTag:"code-review" },
  { categoryId:13, englishText:"Requesting changes",           portugueseText:"Solicitando alterações",          exampleSentence:"I'm requesting changes on this PR.",                              exampleTranslation:"Estou solicitando alterações neste PR.",                       verbTense:"Present Continuous",type:"Expression",  difficulty:1, contextTag:"code-review" },

  // ── Category 14: Incident Management ──────────────────────────────────
  { categoryId:14, englishText:"The service is down",          portugueseText:"O serviço está fora do ar",       exampleSentence:"The service is down for about 15 minutes.",                       exampleTranslation:"O serviço está fora do ar há 15 minutos.",                    verbTense:"Present",           type:"Phrase",      difficulty:1, contextTag:"incident" },
  { categoryId:14, englishText:"We have an outage",            portugueseText:"Temos uma queda de serviço",      exampleSentence:"We have an outage in the payment service.",                       exampleTranslation:"Temos uma queda no serviço de pagamento.",                     verbTense:"Present",           type:"Phrase",      difficulty:1, contextTag:"incident" },
  { categoryId:14, englishText:"ETA for fix",                  portugueseText:"Estimativa para a correção",      exampleSentence:"What is the ETA for the fix?",                                    exampleTranslation:"Qual é a estimativa para a correção?",                         verbTense:"",                  type:"Acronym",     difficulty:1, contextTag:"incident" },
  { categoryId:14, englishText:"root cause analysis (RCA)",    portugueseText:"análise de causa raiz",           exampleSentence:"We need to write the RCA by Friday.",                             exampleTranslation:"Precisamos escrever a análise de causa raiz até sexta.",       verbTense:"",                  type:"Acronym",     difficulty:2, contextTag:"incident" },
  { categoryId:14, englishText:"post-mortem",                  portugueseText:"relatório pós-morte / post-mortem", exampleSentence:"The post-mortem is scheduled for Thursday.",                   exampleTranslation:"O post-mortem está agendado para quinta-feira.",               verbTense:"",                  type:"Expression",  difficulty:2, contextTag:"incident" },
  { categoryId:14, englishText:"rolling back the deployment",  portugueseText:"revertendo o deploy",             exampleSentence:"We are rolling back the deployment now.",                         exampleTranslation:"Estamos revertendo o deploy agora.",                           verbTense:"Present Continuous",type:"Phrase",      difficulty:2, contextTag:"incident" },
  { categoryId:14, englishText:"Customers are impacted",       portugueseText:"Clientes estão sendo impactados", exampleSentence:"Customers are impacted in the US region.",                        exampleTranslation:"Clientes na região dos EUA estão sendo impactados.",           verbTense:"Present",           type:"Phrase",      difficulty:1, contextTag:"incident" },
  { categoryId:14, englishText:"false alarm",                  portugueseText:"falso alarme",                    exampleSentence:"Fortunately it was a false alarm.",                               exampleTranslation:"Felizmente foi um falso alarme.",                              verbTense:"Past Simple",       type:"Expression",  difficulty:1, contextTag:"incident" },
  { categoryId:14, englishText:"All systems operational",      portugueseText:"Todos os sistemas operacionais",  exampleSentence:"All systems operational — incident resolved.",                    exampleTranslation:"Todos os sistemas operacionais — incidente resolvido.",         verbTense:"Present",           type:"Phrase",      difficulty:1, contextTag:"incident" },
  { categoryId:14, englishText:"SLA breach",                   portugueseText:"violação de SLA",                 exampleSentence:"This outage caused an SLA breach.",                               exampleTranslation:"Essa queda causou uma violação de SLA.",                       verbTense:"Past Simple",       type:"Expression",  difficulty:2, contextTag:"incident" },
  { categoryId:14, englishText:"escalating to on-call engineer",portugueseText:"escalonando para o engenheiro de plantão", exampleSentence:"I'm escalating to the on-call engineer.",           exampleTranslation:"Estou escalonando para o engenheiro de plantão.",              verbTense:"Present Continuous",type:"Phrase",      difficulty:2, contextTag:"incident" },
  { categoryId:14, englishText:"hotfix",                       portugueseText:"correção urgente / hotfix",       exampleSentence:"We need to ship a hotfix tonight.",                               exampleTranslation:"Precisamos lançar um hotfix hoje à noite.",                    verbTense:"",                  type:"Expression",  difficulty:1, contextTag:"incident" },
  { categoryId:14, englishText:"We identified the culprit",    portugueseText:"Identificamos o culpado",         exampleSentence:"We identified the culprit — it was a memory leak.",               exampleTranslation:"Identificamos o culpado — era um vazamento de memória.",       verbTense:"Past Simple",       type:"Phrase",      difficulty:2, contextTag:"incident" },
  { categoryId:14, englishText:"monitoring for 30 minutes",    portugueseText:"monitorando por 30 minutos",      exampleSentence:"We are monitoring for 30 minutes before closing the incident.",   exampleTranslation:"Estamos monitorando por 30 minutos antes de fechar o incidente.", verbTense:"Present Continuous", type:"Phrase", difficulty:1, contextTag:"incident" },

  // ── Category 15: Business Communication ────────────────────────────────
  { categoryId:15, englishText:"Let's schedule a meeting",      portugueseText:"Vamos agendar uma reunião",       exampleSentence:"Let's schedule a meeting to discuss the proposal.",              exampleTranslation:"Vamos agendar uma reunião para discutir a proposta.",         verbTense:"Present",           type:"Phrase",      difficulty:1, contextTag:"meeting" },
  { categoryId:15, englishText:"What time works for you?",      portugueseText:"Que hora funciona para você?",    exampleSentence:"What time works for you next Tuesday?",                          exampleTranslation:"Que hora funciona para você na próxima terça?",              verbTense:"Present Simple",    type:"Phrase",      difficulty:1, contextTag:"meeting" },
  { categoryId:15, englishText:"I've attached the documents",   portugueseText:"Anexei os documentos",           exampleSentence:"I've attached the documents to the email.",                      exampleTranslation:"Anexei os documentos ao email.",                             verbTense:"Present Perfect",   type:"Phrase",      difficulty:1, contextTag:"communication" },
  { categoryId:15, englishText:"Could you review this?",        portugueseText:"Você poderia revisar isso?",     exampleSentence:"Could you review this proposal by Friday?",                     exampleTranslation:"Você poderia revisar essa proposta até sexta?",             verbTense:"Conditional",       type:"Phrase",      difficulty:1, contextTag:"request" },
  { categoryId:15, englishText:"I appreciate your feedback",    portugueseText:"Agradeço seu feedback",          exampleSentence:"I appreciate your feedback on this topic.",                      exampleTranslation:"Agradeço seu feedback sobre esse tópico.",                  verbTense:"Present Simple",    type:"Phrase",      difficulty:1, contextTag:"appreciation" },
  { categoryId:15, englishText:"Let me know if you have questions", portugueseText:"Me avise se você tiver dúvidas", exampleSentence:"Let me know if you have any questions about the project.", exampleTranslation:"Me avise se você tiver alguma dúvida sobre o projeto.", verbTense:"Imperative",        type:"Phrase",      difficulty:1, contextTag:"communication" },
  { categoryId:15, englishText:"I wanted to follow up on...",   portugueseText:"Queria dar um seguimento em...",  exampleSentence:"I wanted to follow up on our conversation yesterday.",           exampleTranslation:"Queria dar um seguimento na nossa conversa de ontem.",       verbTense:"Past Simple",       type:"Phrase",      difficulty:2, contextTag:"follow-up" },
  { categoryId:15, englishText:"Could we move this to next week?", portugueseText:"Poderíamos adiar isso para a próxima semana?", exampleSentence:"Could we move this meeting to next week?", exampleTranslation:"Poderíamos adiar essa reunião para a próxima semana?", verbTense:"Conditional", type:"Phrase", difficulty:1, contextTag:"meeting" },
  { categoryId:15, englishText:"I understand your concerns",    portugueseText:"Entendo suas preocupações",       exampleSentence:"I understand your concerns about the timeline.",                 exampleTranslation:"Entendo suas preocupações com o cronograma.",                verbTense:"Present Simple",    type:"Phrase",      difficulty:2, contextTag:"discussion" },
  { categoryId:15, englishText:"Could this be improved?",       portugueseText:"Isso poderia ser melhorado?",     exampleSentence:"Could this presentation be improved?",                          exampleTranslation:"Essa apresentação poderia ser melhorada?",                  verbTense:"Conditional",       type:"Phrase",      difficulty:2, contextTag:"suggestion" },
  { categoryId:15, englishText:"I'm happy to help",             portugueseText:"Fico feliz em ajudar",           exampleSentence:"I'm happy to help with this task.",                             exampleTranslation:"Fico feliz em ajudar com essa tarefa.",                      verbTense:"Present Simple",    type:"Phrase",      difficulty:1, contextTag:"offer" },
  { categoryId:15, englishText:"Let's sync later today",        portugueseText:"Vamos sincronizar mais tarde hoje", exampleSentence:"Let's sync later today to align our priorities.",             exampleTranslation:"Vamos sincronizar mais tarde hoje para alinhar prioridades.", verbTense:"Present",           type:"Phrase",      difficulty:1, contextTag:"meeting" },

  // ── Category 16: Tense Tips & Tricks ───────────────────────────────────
  { categoryId:16, englishText:"Use Present Continuous with 'currently', 'right now', 'this week'", portugueseText:"Use Present Continuous com 'currently', 'right now', 'this week'", exampleSentence:"I am currently working on a new project - this is Present Continuous.", exampleTranslation:"Estou trabalhando em um novo projeto no momento - isso é Present Continuous.", verbTense:"Present Continuous", type:"Tip", difficulty:2, contextTag:"tenses" },
  { categoryId:16, englishText:"Use Present Simple with 'usually', 'normally', 'every day'", portugueseText:"Use Present Simple com 'usually', 'normally', 'every day'", exampleSentence:"I usually work from home - this is Present Simple for habits.", exampleTranslation:"Normalmente trabalho de casa - isso é Present Simple para hábitos.", verbTense:"Present Simple", type:"Tip", difficulty:1, contextTag:"tenses" },
  { categoryId:16, englishText:"Use Past Simple when you answer 'when' - use Present Perfect when you don't say when", portugueseText:"Use Past Simple quando você responde 'when' - use Present Perfect quando não diz quando", exampleSentence:"When did you fix the bug? Last night. (Past Simple) vs Have you fixed it? Yes, I have. (Present Perfect)", exampleTranslation:"Quando você corrigiu o bug? Ontem à noite. (Past Simple) vs Você corrigiu? Sim, corrigi. (Present Perfect)", verbTense:"Comparison", type:"Tip", difficulty:3, contextTag:"tenses" },
  { categoryId:16, englishText:"Use Going To for plans - use Future Simple for promises", portugueseText:"Use Going To para planos - use Future Simple para promessas", exampleSentence:"We are going to meet the client (plan) vs We will get back to you ASAP (promise)", exampleTranslation:"Vamos encontrar o cliente (plano) vs Vamos responder você ASAP (promessa)", verbTense:"Comparison", type:"Tip", difficulty:2, contextTag:"tenses" },
  { categoryId:16, englishText:"Form Present Continuous: Subject + am/is/are + Verb+ing", portugueseText:"Formar Present Continuous: Subject + am/is/are + Verb+ing", exampleSentence:"I am working. She is testing. We are deploying.", exampleTranslation:"Estou trabalhando. Ela está testando. Estamos fazendo deploy.", verbTense:"Present Continuous", type:"Rule", difficulty:1, contextTag:"grammar" },
  { categoryId:16, englishText:"Form Present Simple: I/You/We/They + Verb OR He/She/It + Verb+s", portugueseText:"Formar Present Simple: I/You/We/They + Verb OU He/She/It + Verb+s", exampleSentence:"I go to the gym. She goes frequently. It rains a lot.", exampleTranslation:"Vou à academia. Ela vai frequentemente. Chove muito.", verbTense:"Present Simple", type:"Rule", difficulty:1, contextTag:"grammar" },
  { categoryId:16, englishText:"Use Modal verbs to soften requests and suggestions", portugueseText:"Use verbos modais para suavizar pedidos e sugestões", exampleSentence:"Could you review this? (more polite) vs You must review this (harsh)", exampleTranslation:"Você poderia revisar isso? (mais educado) vs Você deve revisar isso (áspero)", verbTense:"Conditional", type:"Tip", difficulty:2, contextTag:"politeness" },
  { categoryId:16, englishText:"Past Perfect Continuous emphasizes duration before another past event", portugueseText:"Past Perfect Continuous enfatiza duração antes de outro evento passado", exampleSentence:"We had been working on this for 3 hours when the boss arrived.", exampleTranslation:"Estávamos trabalhando nisto há 3 horas quando o chefe chegou.", verbTense:"Past Perfect Continuous", type:"Tip", difficulty:3, contextTag:"tenses" },
  { categoryId:16, englishText:"Contractions in speaking: can't, won't, isn't, haven't", portugueseText:"Contrações na fala: can't, won't, isn't, haven't", exampleSentence:"I can't do it now. It isn't working. We haven't finished yet.", exampleTranslation:"Não posso fazer agora. Não está funcionando. Ainda não terminamos.", verbTense:"", type:"Vocabulary", difficulty:1, contextTag:"speaking" },
]

export const EXERCISES: SEInput[] = [
  // Code Review
  { categoryId:13, englishSentence:"I left some comments for you to address",       portugueseSentence:"Deixei alguns comentários para você resolver",          verbTense:"Past Simple",          contextTag:"code-review",    difficulty:1, tip:"Use 'left' (Past Simple of leave) when talking about comments already written." },
  { categoryId:13, englishSentence:"Could you add unit tests for this edge case",   portugueseSentence:"Você poderia adicionar testes unitários para esse caso extremo", verbTense:"Conditional", contextTag:"code-review",    difficulty:2, tip:"'Could you' is a polite way to request something in code reviews." },
  { categoryId:13, englishSentence:"This logic is hard to follow",                  portugueseSentence:"Essa lógica é difícil de acompanhar",                   verbTense:"Present Simple",       contextTag:"code-review",    difficulty:1, tip:"'Hard to follow' means difficult to understand." },
  { categoryId:13, englishSentence:"Please follow the naming conventions",          portugueseSentence:"Por favor, siga as convenções de nomenclatura",          verbTense:"Imperative",           contextTag:"code-review",    difficulty:1, tip:"Imperative form is commonly used in review requests." },
  { categoryId:13, englishSentence:"I approved the PR with minor suggestions",      portugueseSentence:"Aprovei o PR com sugestões menores",                    verbTense:"Past Simple",          contextTag:"code-review",    difficulty:2, tip:"Past Simple for completed review actions." },
  { categoryId:13, englishSentence:"Remove the dead code before merging",           portugueseSentence:"Remova o código morto antes de fazer merge",            verbTense:"Imperative",           contextTag:"code-review",    difficulty:1, tip:"Imperative + 'before' + gerund is a very common review instruction pattern." },
  { categoryId:13, englishSentence:"The naming could be much clearer here",         portugueseSentence:"O nome poderia ser muito mais claro aqui",              verbTense:"Conditional",          contextTag:"code-review",    difficulty:2, tip:"'Could be' (conditional) softens criticism — more polite than 'is not clear'." },
  // Incident Management
  { categoryId:14, englishSentence:"The service has been down for two hours",       portugueseSentence:"O serviço está fora do ar há duas horas",               verbTense:"Present Perfect",      contextTag:"incident",       difficulty:2, tip:"Use Present Perfect ('has been') for situations that started in the past and continue now." },
  { categoryId:14, englishSentence:"We are rolling back the deployment right now",  portugueseSentence:"Estamos revertendo o deploy agora mesmo",               verbTense:"Present Continuous",   contextTag:"incident",       difficulty:2, tip:"Present Continuous for actions happening at this exact moment." },
  { categoryId:14, englishSentence:"Customers have been affected since midnight",   portugueseSentence:"Os clientes estão sendo afetados desde meia-noite",     verbTense:"Present Perfect",      contextTag:"incident",       difficulty:3, tip:"Present Perfect + 'since' for a situation ongoing since a point in time." },
  { categoryId:14, englishSentence:"We identified the root cause of the outage",    portugueseSentence:"Identificamos a causa raiz da queda",                   verbTense:"Past Simple",          contextTag:"incident",       difficulty:2, tip:"Past Simple for a completed investigation action." },
  { categoryId:14, englishSentence:"All systems are back to normal",                portugueseSentence:"Todos os sistemas voltaram ao normal",                  verbTense:"Present Simple",       contextTag:"incident",       difficulty:1, tip:"Use 'are back to normal' to announce incident resolution." },
  { categoryId:14, englishSentence:"We will write the post-mortem by tomorrow",     portugueseSentence:"Vamos escrever o post-mortem até amanhã",               verbTense:"Future Simple",        contextTag:"incident",       difficulty:2, tip:"'Will + infinitive' for future commitments." },
  { categoryId:14, englishSentence:"I am escalating this to the on-call team",      portugueseSentence:"Estou escalonando isso para o time de plantão",         verbTense:"Present Continuous",   contextTag:"incident",       difficulty:2, tip:"Present Continuous for actions in progress right now during an incident." },
  // Daily Standup
  { categoryId:1,  englishSentence:"I am waiting for the PR to be reviewed",        portugueseSentence:"Estou esperando o PR ser revisado",                     verbTense:"Present Continuous",   contextTag:"standup",        difficulty:1, tip:"Use Present Continuous for ongoing waits." },
  { categoryId:1,  englishSentence:"I might miss the deadline this Friday",          portugueseSentence:"Posso não cumprir o prazo nessa sexta",                 verbTense:"Present",              contextTag:"standup",        difficulty:2, tip:"'Might' expresses possibility — use it when unsure about completing on time." },
  { categoryId:1,  englishSentence:"My blocker is waiting for the API credentials",  portugueseSentence:"Meu impedimento é aguardar as credenciais da API",      verbTense:"Present Simple",       contextTag:"standup",        difficulty:2, tip:"Common standup structure: My blocker is + [noun/gerund]." },
  { categoryId:1,  englishSentence:"I will have finished the feature by end of day", portugueseSentence:"Terei terminado a funcionalidade até o fim do dia",     verbTense:"Future Perfect",       contextTag:"standup",        difficulty:3, tip:"'Will have + past participle' (Future Perfect) = action completed before a future time." },
  // Retrospectiva
  { categoryId:2,  englishSentence:"We should have caught that bug earlier",         portugueseSentence:"Deveríamos ter detectado esse bug antes",               verbTense:"Modal Perfect",        contextTag:"retrospective",  difficulty:3, tip:"'Should have + past participle' expresses regret or missed opportunity." },
  { categoryId:2,  englishSentence:"The deployment process was too manual",          portugueseSentence:"O processo de deploy era muito manual",                 verbTense:"Past Simple",          contextTag:"retrospective",  difficulty:1, tip:"Use Past Simple with 'was' to describe how things were in the last sprint." },
  { categoryId:2,  englishSentence:"We had been ignoring the test coverage",         portugueseSentence:"Estávamos ignorando a cobertura de testes",             verbTense:"Past Perfect Continuous", contextTag:"retrospective",difficulty:3, tip:"Past Perfect Continuous for ongoing issues before a reference point in the past." },
  // Sprint Planning
  { categoryId:3,  englishSentence:"This story needs to be split into smaller tasks",portugueseSentence:"Essa história precisa ser dividida em tarefas menores",  verbTense:"Present Simple",       contextTag:"planning",       difficulty:2, tip:"'Needs to be + past participle' is the passive voice for requirements." },
  { categoryId:3,  englishSentence:"What are the acceptance criteria for this task", portugueseSentence:"Quais são os critérios de aceitação para essa tarefa",  verbTense:"Present Simple",       contextTag:"planning",       difficulty:2, tip:"Standard planning question structure: What are the [criteria] for [task]?" },
  { categoryId:3,  englishSentence:"We need to define the scope before estimating",  portugueseSentence:"Precisamos definir o escopo antes de estimar",          verbTense:"Present Simple",       contextTag:"planning",       difficulty:2, tip:"'Need to' for necessity, 'before + gerund' for sequence." },
  // Tech Vocabulary
  { categoryId:12, englishSentence:"The memory leak caused the service to crash",    portugueseSentence:"O vazamento de memória fez o serviço travar",           verbTense:"Past Simple",          contextTag:"debugging",      difficulty:2, tip:"'Cause + object + to + infinitive' is a common cause-effect structure." },
  { categoryId:12, englishSentence:"We use feature flags to roll out gradually",     portugueseSentence:"Usamos flags de funcionalidade para lançar gradualmente", verbTense:"Present Simple",     contextTag:"devops",         difficulty:2, tip:"Use 'to + infinitive' to explain purpose." },
  { categoryId:12, englishSentence:"The API endpoint must be idempotent",             portugueseSentence:"O endpoint da API deve ser idempotente",                verbTense:"Modal",                contextTag:"api",            difficulty:3, tip:"'Must be + adjective' for requirements." },
  { categoryId:12, englishSentence:"Containerization makes deployments reproducible", portugueseSentence:"A conteinerização torna os deploys reproduzíveis",      verbTense:"Present Simple",       contextTag:"devops",         difficulty:3, tip:"'Makes + object + adjective' is a common pattern to describe benefits." },
  // Future Tenses
  { categoryId:8,  englishSentence:"By the end of the quarter we will have shipped three features", portugueseSentence:"Até o final do trimestre teremos lançado três funcionalidades", verbTense:"Future Perfect", contextTag:"planning", difficulty:3, tip:"Future Perfect: will + have + past participle. Used to describe completion before a future point." },
  // Conditionals
  { categoryId:9,  englishSentence:"If we had added more tests we would not have shipped the bug",  portugueseSentence:"Se tivéssemos adicionado mais testes não teríamos lançado o bug", verbTense:"Third Conditional", contextTag:"retrospective", difficulty:3, tip:"Third Conditional: if + had + past participle, would + have + past participle. Regret about the past." },
  // Modal Verbs
  { categoryId:10, englishSentence:"You should have written tests before submitting the PR", portugueseSentence:"Você deveria ter escrito testes antes de enviar o PR", verbTense:"Modal Perfect", contextTag:"code-review", difficulty:3, tip:"'Should have + past participle' = missed obligation or regret." },
  // Business Communication
  { categoryId:15, englishSentence:"I have attached the documents to the email",           portugueseSentence:"Anexei os documentos ao email",                            verbTense:"Present Perfect",      contextTag:"communication",  difficulty:1, tip:"Present Perfect for recent actions: 'have + past participle'." },
  { categoryId:15, englishSentence:"Could you review the proposal by tomorrow?",          portugueseSentence:"Você poderia revisar a proposta até amanhã?",            verbTense:"Conditional",          contextTag:"request",        difficulty:1, tip:"'Could you' is a polite way to request something. Use 'by + time' for deadlines." },
  { categoryId:15, englishSentence:"I wanted to follow up on our meeting yesterday",      portugueseSentence:"Queria dar um seguimento na sua reunião de ontem",     verbTense:"Past Simple",          contextTag:"follow-up",      difficulty:1, tip:"'I wanted to' is a polite way to introduce a follow-up." },
  { categoryId:15, englishSentence:"Let's schedule a meeting to discuss the strategy",   portugueseSentence:"Vamos agendar uma reunião para discutir a estratégia",  verbTense:"Imperative",           contextTag:"meeting",        difficulty:1, tip:"Imperative 'Let's' for proposing actions." },
  { categoryId:15, englishSentence:"I appreciate your feedback on this topic",            portugueseSentence:"Agradeço seu feedback sobre esse tópico",                verbTense:"Present Simple",       contextTag:"appreciation",   difficulty:1, tip:"'I appreciate' is a professional way to thank someone." },
  { categoryId:15, englishSentence:"We could move this meeting to next week if needed",  portugueseSentence:"Poderíamos adiar essa reunião para a próxima semana se necessário", verbTense:"Conditional",  contextTag:"meeting", difficulty:2, tip:"Conditional + 'if needed' is very polite for proposing changes." },
  // Tense Tips & Tricks
  { categoryId:16, englishSentence:"I am currently working on the migration project",    portugueseSentence:"Estou atualmente trabalhando no projeto de migração",    verbTense:"Present Continuous",   contextTag:"tenses",         difficulty:1, tip:"Use Present Continuous with 'currently' to describe what's happening now." },
  { categoryId:16, englishSentence:"She usually reviews code every morning",              portugueseSentence:"Ela normalmente revisa código toda manhã",              verbTense:"Present Simple",       contextTag:"tenses",         difficulty:1, tip:"Use Present Simple with 'usually' for regular habits or routines." },
  { categoryId:16, englishSentence:"When did you deploy? Yesterday at 3 PM",             portugueseSentence:"Quando você fez deploy? Ontem às 3 da tarde",           verbTense:"Past Simple",          contextTag:"tenses",         difficulty:1, tip:"Use Past Simple when answering 'when' questions with specific past times." },
  { categoryId:16, englishSentence:"Have you finished the tests? Yes, I have completed them", portugueseSentence:"Você terminou os testes? Sim, eu os completei", verbTense:"Present Perfect", contextTag:"tenses", difficulty:2, tip:"Use Present Perfect when the exact time is not mentioned and the action is recent." },
  { categoryId:16, englishSentence:"We are going to refactor the module next sprint",   portugueseSentence:"Vamos refatorar o módulo no próximo sprint",              verbTense:"Going To",             contextTag:"tenses",         difficulty:1, tip:"'Going to' is used for plans and intentions." },
  { categoryId:16, englishSentence:"I will help you with the deployment tomorrow",       portugueseSentence:"Vou ajudar você com o deploy amanhã",                  verbTense:"Future Simple",        contextTag:"tenses",         difficulty:1, tip:"'Will + infinitive' is used for promises and instant decisions." },
  { categoryId:16, englishSentence:"We had been working for 8 hours when the bug appeared", portugueseSentence:"Tínhamos estado trabalhando por 8 horas quando o bug apareceu", verbTense:"Past Perfect Continuous", contextTag:"tenses", difficulty:3, tip:"Past Perfect Continuous emphasizes duration of an action before another past event." },
  { categoryId:16, englishSentence:"Could you check this? It might be broken.",           portugueseSentence:"Você poderia checar isso? Pode estar quebrado.",           verbTense:"Conditional + Modal", contextTag:"tenses",         difficulty:2, tip:"Modal verbs like 'could' and 'might' are used with various tenses for politeness and probability." },
]
